In [ ]:
##01

In [1]:
import numpy as np

In [3]:
h = [1.73, 1.68, 1.71, 1.89, 1.79]
w = [65.4, 59.2, 63.6, 88.4, 68.7]
h / w ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [10]:
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])

In [19]:
np_weight = np.array([[65.4, 59.2, 63.6, 88.4, 68.7],[65.4, 59.2, 63.6, 88.4, 68.7]])

In [6]:
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [7]:
bmi = np_weight / np_height ** 2

In [8]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [12]:
np_weight + np_height

array([67.13, 60.88, 65.31, 90.29, 70.49])

In [10]:
np.array([1.0, 'yes', True])

array(['1.0', 'yes', 'True'], dtype='<U32')

In [13]:
python_list = [1,2,3]
python_list+python_list

[1, 2, 3, 1, 2, 3]

In [14]:
np_array = np.array([1,2,3])
np_array+np_array

array([2, 4, 6])

In [14]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [15]:
bmi[2]

21.750282138093777

In [16]:
bmi > 23

array([False, False, False,  True, False])

In [17]:
bmi[bmi>23]

array([24.7473475])

In [ ]:
##02

In [17]:
np_2d = np.array([
                [1.73, 1.68, 1.71, 1.89, 1.79],
                [65.4, 59.2, 66.3, 11.2, 7.9]
                ])

In [20]:
np_2d.shape

(2, 5)

In [21]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
         [65.4, 59.2, 66.3, 11.2, '7.9']])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '66.3', '11.2', '7.9']], dtype='<U32')

In [22]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [23]:
np_2d[0][2]

1.71

In [24]:
np_2d[0,2]

1.71

In [25]:
np_2d[:,1:3]

array([[ 1.68,  1.71],
       [59.2 , 66.3 ]])

In [20]:
np_2d[1,:]

array([65.4, 59.2, 66.3, 11.2,  7.9])

In [21]:
np_n = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                [65.4, 59.2, 66.3, 11.2, 7.9],
                 [65.4, 59.2, 66.3, 11.2, 7.9]])

In [32]:
np_n[2,0:2]

array([65.4, 59.2])

In [ ]:
#03

In [3]:
np_n = np.array([[1, 1, 1, 1, 1.79],
                [65.4, 59.2, 66.3, 11.2, 7.9],
                 [65.4, 59.2, 66.3, 11.2, 7.9]])

In [44]:
np.mean(np_n[0,:])

1.158

In [45]:
np.median(np_n[0,:])

1.0

In [42]:
np.corrcoef(np_n[0,:], np_n[1,:])

array([[ 1.        , -0.64029549],
       [-0.64029549,  1.        ]])

In [46]:
np.std(np_n[0,:])

0.316

In [52]:
#mean, std, 個數10, 小數點4
w = np.round(np.random.normal(1,2,10), 4)
w

array([ 1.4425,  0.675 , -0.9692, -0.4285,  1.4422, -0.7218,  2.8205,
        0.0779,  2.226 ,  0.6419])

In [ ]:
#NN

In [ ]:
import numpy

In [ ]:
def NN(m1, m2, w1, w2, b):
    z = m1 * w1 + m2 * w2 + b
    return sigmoid(z)

def sigmoid(x):
    return 1/(1 + numpy.exp(-x))

In [ ]:
w1 = numpy.random.randn() 
w2 = numpy.random.randn() 
b = numpy.random.randn() 

In [ ]:
NN(3,1.5,w1,w2,b)

In [ ]:
phrases = ['看起來像', '我猜是', '我想是', '可能是', '看起來像是', '猜測....']
data = [[3,1.5,1],[2,1,0],[4,1.5,1],[3,1,0],[3.5,5,1],[2,0.5,0],[5.5,1,1],[1,1,0]]
rand_data = data[numpy.random.randint(len(data))] #隨機產生len(data)-1的index
m1 = rand_data[0]
m2 = rand_data[1]

prediction = NN(m1,m2,w1,w2,b)
prediction_text = ['藍色','紅色'][int(numpy.round(prediction))] #取四捨五入後的數值
phrase = numpy.random.choice(phrases) + "" + prediction_text #隨機取phrases
o =('這個' + phrase + "\n真的是"+ ['藍色','紅色'][rand_data[2]])
print(o)

In [ ]:
## Advanced Neural network in numpy

In [ ]:
import numpy as np

#Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y=np.array([[1],[1],[0]])

#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

#Sigmoid Function for backpropagation
def derivatives_sigmoid (x):
    return x * (1 - x)

#Variable initialization
epoch=5000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 10 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons)) #均勻分布
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

for i in range(epoch):
  #Forward Propogation
  hidden_layer_input1=np.dot(X,wh)#做內積
  hidden_layer_input=hidden_layer_input1 + bh
  hiddenlayer_activations = sigmoid(hidden_layer_input)
  output_layer_input1=np.dot(hiddenlayer_activations,wout)
  output_layer_input= output_layer_input1+ bout
  output = sigmoid(output_layer_input)

  #Backpropagation
  E = y-output #Loss差異
  back_output_layer = derivatives_sigmoid(output)
  back_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
  d_output = E * back_output_layer
  Error_at_hidden_layer = d_output.dot(wout.T) #轉置後才能乘back_hidden_layer
  d_hiddenlayer = Error_at_hidden_layer * back_hidden_layer
  wout += hiddenlayer_activations.T.dot(d_output) *lr #乘以學習率之後，再每次迴圈判斷Error
  bout += np.sum(d_output, axis=0,keepdims=True) *lr #乘以學習率之後，再每次迴圈判斷Error
  wh += X.T.dot(d_hiddenlayer) *lr 
  bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr #keepdims保持矩陣二維特性
    
  numpy_E = np.array(E) 
  Loss_E = np.sum((numpy_E)**2)/len(numpy_E)
  print("E",Loss_E)
  
    
print('actual :\n', y, '\n')
print('predicted :\n', output)